Back to **[Fan](https://fanwangecon.github.io/)**'s R4Econ Homepage **[Table of Content](https://fanwangecon.github.io/R4Econ/)**

# By Multiple within Individual Groups Variables, Averages for All Numeric Variables within All Groups of All Group Variables (Long to very Wide)

Suppose you have an individual level final outcome. The individual is observed for N periods, where each period the inputs differ. What inputs impacted the final outcome?
`
Suppose we can divide N periods in which the individual is in the data into a number of years, a number of semi-years, a number of quarters, or uneven-staggered lengths. We might want to generate averages across individuals and within each of these different possible groups averages of inputs. 

Then we want to version of the data where each row is an individual, one of the variables is the final outcome, and the other variables are these different averages: averages for the 1st, 2nd, 3rd year in which indivdiual is in data, averages for 1st, ..., final quarter in which indivdiual is in data.

## Function

This function takes as inputs:

1. **vars.not.groups2avg**: a list of variables that are not the within-indivdiual or across-individual grouping variables, but the variables we want to average over. Withnin indivdiual grouping averages will be calculated for these variables using the not-listed variables as within indivdiual groups (excluding vars.indi.grp groups).
2. **vars.indi.grp**: a list or individual variables, and also perhaps villages, province, etc id variables that are higher than individual ID. Note the groups are are ACROSS individual higher level group variables.
3. the remaining variables are all within individual grouping variables.

the function output is a dataframe:

1. each row is an individual
2. initial variables individual ID and across individual groups from *vars.indi.grp*.
3. other variables are all averages for the variables in *vars.not.groups2avg*
    + if there are 2 within individual group variables, and the first has 3 groups (years), the second has 6 groups (semi-years), then there would be 9 average variables. 
    + each average variables has the original variable name from vars.not.groups2avg plus the name of the within individual grouping variable, and at the end 'c_x', where x is a integer representing the category within the group (if 3 years, x=1, 2, 3)

In [1]:
# Data Function
# https://fanwangecon.github.io/R4Econ/summarize/summ/ByGroupsSummWide.html
f.by.groups.summ.wide <- function(df.groups.to.average,
                                  vars.not.groups2avg,
                                  vars.indi.grp = c('S.country','ID'),
                                  display=TRUE) {

# 1. generate categoricals for full year (m.12), half year (m.6), quarter year (m.4)
# 2. generate categoricals also for uneven years (m12t14) using stagger (+2 rather than -1)
# 3. reshape wide to long, so that all categorical date groups appear in var=value, 
    # and categories in var=variable
# 4. calculate mean for all numeric variables for all date groups
# 5. combine date categorical variable and value, single var: 
    # m.12.c1= first year average from m.12 averaging

######## ######## ######## ######## #######
# Step 1
######## ######## ######## ######## #######
# 1. generate categoricals for full year (m.12), half year (m.6), quarter year (m.4)
# 2. generate categoricals also for uneven years (m12t14) using stagger (+2 rather than -1)

######## ######## ######## ######## #######
# S2: reshape wide to long, so that all categorical date groups appear in var=value, 
    # and categories in var=variable; calculate mean for all numeric variables for all date groups
######## ######## ######## ######## #######
df.avg.long <- df.groups.to.average %>%
       gather(variable, value, -one_of(c(vars.indi.grp, 
                                         vars.not.groups2avg))) %>%
       group_by(!!!syms(vars.indi.grp), variable, value) %>%
       summarise_if(is.numeric, funs(mean(., na.rm = TRUE)))

if (display){
  dim(df.avg.long)
  options(repr.matrix.max.rows=10, repr.matrix.max.cols=20)
  print(df.avg.long)
}

######## ######## ######## ######## #######
# S3 combine date categorical variable and value, single var: 
#    m.12.c1= first year average from m.12 averaging; to do this make data even longer first
######## ######## ######## ######## #######

# We already have the averages, but we want them to show up as variables, 
    # mean for each group of each variable.
df.avg.allvars.wide <- df.avg.long %>%
   ungroup() %>%
   mutate(all_m_cate = paste0(variable, '_c', value)) %>%
   select(all_m_cate, everything(), -variable, -value) %>%
   gather(variable, value, -one_of(vars.indi.grp), -all_m_cate) %>%
   unite('var_mcate', variable, all_m_cate) %>%
   spread(var_mcate, value)

if (display){
  dim(df.avg.allvars.wide)
  options(repr.matrix.max.rows=10, repr.matrix.max.cols=10)
  print(df.avg.allvars.wide)
}

return(df.avg.allvars.wide)
}

## Data

In our sample dataset, the number of nutrition/height/income etc information observed within each country and month of age group are different. 

We have a panel dataset for children observed over different months of age. 

We have two key grouping variables:
1. country: data are observed for guatemala and cebu
2. month-age (survey month round=svymthRound): different months of age at which each individual child is observed

A child could be observed for many months, or just a few months. A child's height information could be observed for more months-of-age than nutritional intake information. 

We eventually want to run regressions where the outcome is height/weight and the input is nutrition. The regressions will be at the month-of-age level. We need to know how many times different variables are observed at the month-of-age level.

In [3]:
# Library
library(tidyverse)

# Load Sample Data
setwd('C:/Users/fan/R4Econ/_data/')
df <- read_csv('height_weight.csv')

Parsed with column specification:
cols(
  S.country = col_character(),
  vil.id = col_double(),
  indi.id = col_double(),
  sex = col_character(),
  svymthRound = col_double(),
  momEdu = col_double(),
  wealthIdx = col_double(),
  hgt = col_double(),
  wgt = col_double(),
  hgt0 = col_double(),
  wgt0 = col_double(),
  prot = col_double(),
  cal = col_double(),
  p.A.prot = col_double(),
  p.A.nProt = col_double()
)

## Generate Within Individual Groups

In the data, children are observed for different number of months since birth. We want to calculate quarterly, semi-year, annual, etc average nutritional intakes. First generate these within-individual grouping variables. We can also generate uneven-staggered calendar groups as shown below.

In [4]:
mth.var <- 'svymthRound'
df.groups.to.average<- df %>%
        filter(!!sym(mth.var) >= 0 & !!sym(mth.var) <= 24)  %>%
        mutate(m12t24=(floor((!!sym(mth.var) - 12) %/% 14) + 1),
               m8t24=(floor((!!sym(mth.var) - 8) %/% 18) + 1),
               m12 = pmax((floor((!!sym(mth.var)-1) %/% 12) + 1), 1),
               m6 = pmax((floor((!!sym(mth.var)-1) %/% 6) + 1), 1),
               m3 = pmax((floor((!!sym(mth.var)-1) %/% 3) + 1), 1))

In [5]:
# Show Results
options(repr.matrix.max.rows=30, repr.matrix.max.cols=20)
vars.arrange <- c('S.country','indi.id','svymthRound')
vars.groups.within.indi <- c('m12t24', 'm8t24', 'm12', 'm6', 'm3')
as.tibble(df.groups.to.average %>% 
          group_by(!!!syms(vars.arrange)) %>%
          arrange(!!!syms(vars.arrange)) %>%
          select(!!!syms(vars.arrange), !!!syms(vars.groups.within.indi)))

Warning message:
"`as.tibble()` is deprecated, use `as_tibble()` (but mind the new semantics).
This warning is displayed once per session."

      S.country indi.id svymthRound m12t24 m8t24 m12 m6  m3
1     Cebu      1        0          0      0     1   1   1
2     Cebu      1        2          0      0     1   1   1
3     Cebu      1        4          0      0     1   1   2
4     Cebu      1        6          0      0     1   1   2
5     Cebu      1        8          0      1     1   2   3
6     Cebu      1       10          0      1     1   2   4
7     Cebu      1       12          1      1     1   2   4
8     Cebu      1       14          1      1     2   3   5
9     Cebu      1       16          1      1     2   3   6
10    Cebu      1       18          1      1     2   3   6
11    Cebu      1       20          1      1     2   4   7
12    Cebu      1       22          1      1     2   4   8
13    Cebu      1       24          1      1     2   4   8
14    Cebu      2        0          0      0     1   1   1
15    Cebu      2        2          0      0     1   1   1
...   ...       ...     ...         ...    ...   ... ... ...
23565 Guatemala 2022     9          0      1     1   2   3
23566 Guatemala 2022    12          1      1     1   2   4
23567 Guatemala 2022    15          1      1     2   3   5
23568 Guatemala 2022    18          1      1     2   3   6
23569 Guatemala 2022    21          1      1     2   4   7
23570 Guatemala 2022    24          1      1     2   4   8
23571 Guatemala 2023     0          0      0     1   1   1
23572 Guatemala 2023     3          0      0     1   1   1
23573 Guatemala 2023     6          0      0     1   1   2
23574 Guatemala 2023     9          0      1     1   2   3
23575 Guatemala 2023    12          1      1     1   2   4
23576 Guatemala 2023    15          1      1     2   3   5
23577 Guatemala 2023    18          1      1     2   3   6
23578 Guatemala 2023    21          1      1     2   4   7
23579 Guatemala 2023    24          1      1     2   4   8

## Within Group Averages

With the within-group averages created, we can generate averages for all variables within these groups.

In [6]:
vars.not.groups2avg <- c('prot', 'cal')
vars.indi.grp <- c('S.country', 'indi.id')
vars.groups.within.indi <- c('m12t24', 'm8t24', 'm12', 'm6', 'm3')

df.groups.to.average.select <- df.groups.to.average %>% 
                        select(one_of(c(vars.indi.grp,
                                        vars.not.groups2avg,
                                        vars.groups.within.indi)))
df.avg.allvars.wide <- f.by.groups.summ.wide(df.groups.to.average.select,
                                             vars.not.groups2avg,
                                             vars.indi.grp, display=TRUE)

# A tibble: 36,414 x 6
# Groups:   S.country, indi.id, variable [?]
   S.country indi.id variable value   prot   cal
   <chr>       <dbl> <chr>    <dbl>  <dbl> <dbl>
 1 Cebu            1 m12          1   5.34 125.
 2 Cebu            1 m12          2 NaN    NaN
 3 Cebu            1 m12t24       0   4.08  88.5
 4 Cebu            1 m12t24       1  12.9  343.
 5 Cebu            1 m3           1   0.6    0.5
 6 Cebu            1 m3           2   3.1   83.2
 7 Cebu            1 m3           3   2.1   70.8
 8 Cebu            1 m3           4  14.0  318.
 9 Cebu            1 m3           5 NaN    NaN
10 Cebu            1 m3           6 NaN    NaN
# ... with 36,404 more rows
# A tibble: 2,023 x 38
   S.country indi.id cal_m12_c1 cal_m12_c2 cal_m12t24_c0 cal_m12t24_c1 cal_m3_c1
   <chr>       <dbl>      <dbl>      <dbl>         <dbl>         <dbl>     <dbl>
 1 Cebu            1      125.        NaN           88.5          343.      0.5
 2 Cebu            2      128.        702.          93.9          649.     63
 3 Cebu            3       98.1       257.          89.7          242.     82.0
 4 Cebu            4      102.        657.          35.2          635.      4.55
 5 Cebu            5      182.        533.         156.           505.      4.5
 6 Cebu            6       70.7       NaN           70.7          NaN       0.5
 7 Cebu            7      293.        330.         304.           315.    167.
 8 Cebu            8      110.        520.          87.5          481.     14.1
 9 Cebu            9       53.0       436.          27.0          398.      0.5
10 Cebu           10       32.3       413.          15.2          373.      0.5
# ... with 2,013 more rows, and 31 more variables: cal_m3_c2 <dbl>,
#   cal_m3_c3 <dbl>, cal_m3_c4 <dbl>, cal_m3_c5 <dbl>, cal_m3_c6 <dbl>,
#   cal_m3_c7 <dbl>, cal_m3_c8 <dbl>, cal_m6_c1 <dbl>, cal_m6_c2 <dbl>,
#   cal_m6_c3 <dbl>, cal_m6_c4 <dbl>, cal_m8t24_c0 <dbl>, cal_m8t24_c1 <dbl>,
#   prot_m12_c1 <dbl>, prot_m12_c2 <dbl>, prot_m12t24_c0 <dbl>,
#   prot_m12t24_c1 <dbl>, prot_m3_c1 <dbl>, prot_m3_c2 <dbl>, prot_m3_c3 <dbl>,
#   prot_m3_c4 <dbl>, prot_m3_c5 <dbl>, prot_m3_c6 <dbl>, prot_m3_c7 <dbl>,
#   prot_m3_c8 <dbl>, prot_m6_c1 <dbl>, prot_m6_c2 <dbl>, prot_m6_c3 <dbl>,
#   prot_m6_c4 <dbl>, prot_m8t24_c0 <dbl>, prot_m8t24_c1 <dbl>

#### Table

This is the tabular version of results

In [7]:
dim(df.avg.allvars.wide)
names(df.avg.allvars.wide)

[1] 2023   38

 [1] "S.country"      "indi.id"        "cal_m12_c1"     "cal_m12_c2"
 [5] "cal_m12t24_c0"  "cal_m12t24_c1"  "cal_m3_c1"      "cal_m3_c2"
 [9] "cal_m3_c3"      "cal_m3_c4"      "cal_m3_c5"      "cal_m3_c6"
[13] "cal_m3_c7"      "cal_m3_c8"      "cal_m6_c1"      "cal_m6_c2"
[17] "cal_m6_c3"      "cal_m6_c4"      "cal_m8t24_c0"   "cal_m8t24_c1"
[21] "prot_m12_c1"    "prot_m12_c2"    "prot_m12t24_c0" "prot_m12t24_c1"
[25] "prot_m3_c1"     "prot_m3_c2"     "prot_m3_c3"     "prot_m3_c4"
[29] "prot_m3_c5"     "prot_m3_c6"     "prot_m3_c7"     "prot_m3_c8"
[33] "prot_m6_c1"     "prot_m6_c2"     "prot_m6_c3"     "prot_m6_c4"
[37] "prot_m8t24_c0"  "prot_m8t24_c1"

In [8]:
options(repr.matrix.max.rows=30, repr.matrix.max.cols=12)
df.avg.allvars.wide

     S.country indi.id cal_m12_c1 cal_m12_c2 cal_m12t24_c0 cal_m12t24_c1 ...
1    Cebu       1      124.80000       NaN    88.50000     342.6000      ...
2    Cebu       2      127.65714  701.7833    93.88333     648.7143      ...
3    Cebu       3       98.08571  257.1167    89.71667     241.5714      ...
4    Cebu       4      101.97143  657.1000    35.18333     635.0429      ...
5    Cebu       5      181.54286  533.0167   156.11667     504.6000      ...
6    Cebu       6       70.68000       NaN    70.68000          NaN      ...
7    Cebu       7      292.61429  329.8000   303.90000     314.8143      ...
8    Cebu       8      109.90000  520.2667    87.48333     480.8571      ...
9    Cebu       9       52.97143  435.8200    27.01667     397.9667      ...
10   Cebu      10       32.27143  412.6833    15.20000     372.9714      ...
11   Cebu      11       58.98571  399.0833    57.11667     352.1000      ...
12   Cebu      12      488.37500       NaN   488.37500          NaN      ...
13   Cebu      13       44.80000  229.3500    47.91667     200.3143      ...
14   Cebu      14      323.48571  493.1500   269.53333     515.1571      ...
15   Cebu      15       72.02857  442.8167    62.46667     398.0429      ...
...  ...       ...     ...        ...        ...           ...
2009 Guatemala 2009          NaN   518.9250        NaN      518.9250     ...
2010 Guatemala 2010     89.00000   676.2250   29.70000      570.6400     ...
2011 Guatemala 2011          NaN   614.2250        NaN      614.2250     ...
2012 Guatemala 2012    514.40000  1035.6250  308.10000     1013.9000     ...
2013 Guatemala 2013    145.12500        NaN  117.10000      229.2000     ...
2014 Guatemala 2014    315.12500   744.5000  181.43333      735.0667     ...
2015 Guatemala 2015          NaN   356.4000        NaN      356.4000     ...
2016 Guatemala 2016          NaN   577.9250        NaN      577.9250     ...
2017 Guatemala 2017     69.13333   865.6500   69.13333      865.6500     ...
2018 Guatemala 2018    129.35000   390.7000    4.10000      356.6750     ...
2019 Guatemala 2019    287.95000   565.0000  237.36667      533.6750     ...
2020 Guatemala 2020     87.77500   668.6250   78.36667      558.1000     ...
2021 Guatemala 2021          NaN   356.7000        NaN      356.7000     ...
2022 Guatemala 2022          NaN        NaN        NaN           NaN     ...
2023 Guatemala 2023    268.67500   452.7667  214.30000      447.5250     ...
     prot_m6_c1 prot_m6_c2 prot_m6_c3 prot_m6_c4 prot_m8t24_c0 prot_m8t24_c1
1     1.850     10.000000        NaN        NaN   1.850        10.000000
2     1.550     11.233333  21.033333  36.333333   1.550        22.866667
3     1.000      5.200000   5.933333  13.166667   1.000         8.100000
4     0.550      8.133333  18.200000  22.000000   0.550        16.111111
5     4.475     15.166667  18.433333  11.866667   4.475        15.155556
6     1.950      6.800000        NaN        NaN   1.950         6.800000
7     8.375      6.233333   7.233333   7.633333   8.375         7.033333
8     0.750      5.833333   9.433333  10.600000   0.750         8.622222
9     0.500      4.633333  11.866667  19.050000   0.500        10.950000
10    1.075      1.266667   8.733333  27.866667   1.075        12.622222
11    0.500      3.600000   5.900000  11.066667   0.500         6.855556
12   12.275           NaN        NaN        NaN  12.275              NaN
13    0.550      1.800000   4.333333   6.300000   0.550         4.144444
14    7.975     18.100000  20.933333  15.733333   7.975        18.255556
15    1.450      2.566667   6.333333  16.266667   1.450         8.388889
...  ...        ...        ...        ...        ...           ...
2009  NaN         NaN      11.90      21.20       NaN          16.55000
2010 0.70        8.20      18.90      40.20      0.70          25.28000
2011  NaN         NaN      19.90      40.70       NaN          30.30000
2012 0.60       18.80      21.40      35.60      0.60          25.26667
2013 5.35       10.15        NaN        NaN      5.35          10.15000
2014 5.75       18.55      29.60        NaN      5.75          24.07500
2015  NaN         NaN      11.55      19.65       NaN          15.60000
2016  NaN         NaN      24.30      26.45       NaN          25.37500
2017 5.45        5.20      45.15      46.00      5.45          37.50000
2018 0.70        9.00       8.20      23.10      0.70          12.12500
2019 7.50       11.00      17.25      21.60      7.50          15.62000
2020 4.40        4.65      15.35      34.80      4.40          18.26667
2021  NaN         NaN      11.65        NaN       NaN          11.65000
2022  NaN         NaN        NaN        NaN       NaN               NaN
2023 9.65       12.80      18.90      19.30      9.65          16.54000